### PR TITLE
Adds error indicator to visualize failed requests

### PR DESCRIPTION
**Pull request by mattorchard**
# Description
Adds an error indicator with a count of errors in the request body.
Assumes errors will match the format described in the [graphql spec](https://github.com/graphql/graphql-spec/blob/main/spec/Section%207%20--%20Response.md#errors).
Hovering the count shows a tooltip with the error messages shown.

error-count-preview

# Todos
- [x] Add unit tests
- [x] Update existing unit tests
- [x] Test in standalone
- [x] Test in devtools
- [ ] Update manifest version
- [ ] Update promo images
- [ ] Make new item in mock-requests more unique from others

### CODE REVIEW

**Comment by mattorchard** [comment]
Now that I've used the modified version a bit longer,
I think it would be nicer if the indicator appeared in the first column,
so it could still be visible while there is a selected request.

**Comment by warrenday** [comment]
Hey @mattorchard thanks for raising this PR. It's a really useful feature. I had no idea about the "title" html prop.

In terms of the status colours, the intention was that each colour corresponds to a particular status, i.e. 200 green, 400 red. I don't think that same UI works for the case of errors.

In most cases the green dot and accompanied 0 seems like redundant information.

Could we reconsider how we display the error count? I was thinking just a "-" would be fine for the case of no errors, then potentially red text for when there is an error?

Otherwise we could look at classic icons like a circled "!" when an error is returned.

What are your thoughts?

**Comment by mattorchard** [comment]
@warrenday I agree that the green dot and zero is probably not useful info, and could be made more subtle.

I do like the red dot with exclamation idea, though having the count of errors _might_ still be useful info.
Though maybe more useful would be some way of differentiating between:
* only errors returned
* errors and data returned


Here's a couple test screenshots
image
image

Let me know what you think of having this data in the first column (so that it can be seen even when something is selected).
And what you think about counts / exclamations.

**Comment by warrenday** [comment]
Agree the count is more important than an icon here.

I like the idea of adding it to the first column as you've shown since we don't need to clutter the UI in the case of no errors (and as you say we can keep the error displayed in single column view)

The example screenshots look good 🙌

**Comment by mattorchard** [comment]
Updated the code and the PR description / title to reflect the changes!
@warrenday let me know if it needs any more changes😀

**Review by warrenday — APPROVED** [review]
Awesome work @mattorchard. I'll release this to the webstore this week.

**Pull request merged**
