### PR TITLE
WIP: Search enhancements

### PR DESCRIPTION
**Pull request by mattorchard**
# Work in Progress PR

## Note
- Built on top of changes from PR #60

## Description
- Adds search highlighting
- Fixes bug where scroll panel scroll position is reset when search menu opens/closes
  - Bug was caused by panels unmounting/remounting
  - Resolved by replacing split panel library
- Makes copy buttons stay in corner while scrolling

## Screenshot
(TODO)
image

Provide a screenshot or gif of the new feature in both dark and light mode.

## Checklist

- [ ] Displays correctly with both dark and light mode (see useTheme.ts)  
- [ ] Unit/Integration tests added

### CODE REVIEW

**Comment by warrenday** [comment]
Just so you're aware I'm switching react code blocks out for highlight.js and rending the code in a web worker as performance is drastically improved for large json blobs.

I don't think this will have too much effect on this PR other than the style to highlight the searched text. 

I'll update with more info when I get something ready to merge and we can discuss how the two can work together.

But this is great I've had it on my todo for a while so nice to see it happening!

**Comment by mattorchard** [comment]
Sounds good! 

It may make sense to calculate the lines to highlight inside the web worker too (if the response text is already available in the worker). 
But maybe that's a future optimization to consider 😄

**Comment by warrenday** [comment]
Yeah the full markup will be in the worker, but the main reason for doing this is parsing the json and building the markup is completely render blocking.

I think highlighting the text can be done in an asynchronous way so it should be ok to keep in the main thread since the code at that point would already be rendered to the dom.

I'll try to get something up in the next couple of days so we can discuss the best solution.

**Comment by warrenday** [comment]
Closing as stale

**Pull request closed without merging**
